#!/usr/bin/env php
<?php

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

//require 'vendor/autoload.php';
//require __DIR__ . '/src/RerunCommand.php';
//require __DIR__ . '/src/RerunTestRunner.php';
//require __DIR__ . '/src/FailureListener.php';
//require __DIR__ . '/src/CacheUtil.php';

Rerun_Command::main();